spring:
  application:
    name: dataProvider
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
  datasource:
    url: jdbc:postgresql://${BIBLIO_DB_DATAPROVIDER_SERVICE_HOST}:${BIBLIO_DB_DATAPROVIDER_SERVICE_PORT}/${BIBLIO_DB_DATAPROVIDER_POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      login-timeout: 30000
  sql:
    init:
      platform: postgres
      mode: never
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: true
management:
  endpoint:
    audit:
      enabled: true
ssh:
  shell:
    enabled: true
    command:
      timeout: 60000
    history-file: <java.io.tmpdir>/sshShellHistory.log
